.PHONY: clean All

All:
	@echo "----------Building project:[ syspr - Debug ]----------"
	@cd "syspr" && "$(MAKE)" -f  "syspr.mk"
clean:
	@echo "----------Cleaning project:[ syspr - Debug ]----------"
	@cd "syspr" && "$(MAKE)" -f  "syspr.mk" clean
